### Exercise 4

1. Create a null vector / 1D array size 10 and update fifth value to 11. 

In [1]:
import numpy as np

In [167]:
# Create a null vector / 1 D array size 10
soal1 = np.zeros(10)
print(soal1)

# Update fifth value to 11
soal1[6] = 11
print(soal1)

print("size: ",soal1.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
size:  10


2. Write a Numpy program to create a 2x3 arrays and change it into 3x2 arrays

In [168]:
# Create a 2x3 arrays
soal2 = np.arange(6).reshape(2,3)
print(soal2)
print("shape: ",soal2.shape)

[[0 1 2]
 [3 4 5]]
shape:  (2, 3)


In [169]:
# Change into 3x2 array
soal2a = np.reshape(soal2,(3,2))
print(soal2a)
print("shape: ",soal2a.shape)

[[0 1]
 [2 3]
 [4 5]]
shape:  (3, 2)


3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [143]:
# Create 2D array with 1
soal3 = np.ones((5,5))
print("Original array:")
print(soal3)
print("shape: ",soal3.shape)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape:  (5, 5)


In [170]:
# Change the inside to 0
soal3[1:-1,1:-1]=0
print("1 on the border and 0 inside in the array")
print(soal3)
print("shape: ",soal3.shape)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
shape:  (5, 5)


4. Take a look at the following matrix, Access the [2,1,1]

In [69]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
print(z)

[[[ 0  1  3]
  [ 5  7  9]
  [ 6  8 10]]

 [[ 0  2  4]
  [ 6  8 10]
  [ 0  1  3]]

 [[ 1  1  2]
  [ 5  2  9]
  [ 1  3  3]]]


In [147]:
# Access the [2,1,1] from object "z" above
soal4 = z[2,1,1]=88
print("I access [2,1,1] by change with: ",soal4)
print(z)
print("shape: ",z.shape)

I access [2,1,1] by change with:  88
[[[ 0  1  3]
  [ 5  7  9]
  [ 6  8 10]]

 [[ 0  2  4]
  [ 6  8 10]
  [ 0  1  3]]

 [[ 1  1  2]
  [ 5 88  9]
  [ 1  3  3]]]
shape:  (3, 3, 3)


### Assigment

1. Create a 4x4 matrix with values ranging from 0 to 3.
(The following image is just as an example. It doesn't represent the real image of arrays in the question) 

In [108]:
# 4x4 matrix with values ranging from 0-3
assign1 = np.zeros((4,4))
print("Create a 4x4 matrix")
print(assign1)
print("")

print("Change values ranging from 0 to 3")
assign1 += np.arange(4)
print(assign1)

Create a 4x4 matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Change values ranging from 0 to 3
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [166]:
# Create array with shape of 4x4
assign2 = np.arange(3,19).reshape((4,4))
print("Original 4x4 array")
print(assign2)
print("shape:",assign2.shape)
print("")

# Turn it into two arrays along the second axis
assign3 = np.hsplit(assign2,[2])
print("Splitting into 2 arrays along the second axis")
print(assign3)

Original 4x4 array
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
shape: (4, 4)

Splitting into 2 arrays along the second axis
[array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]]), array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])]
